# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 14:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itinisere_id', models.IntegerField()),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('bus', 'Bus'), ('car', 'Car'), ('tram', 'Tramway'), ('train', 'Train')], max_length=20)),
                ('operator', models.CharField(blank=True, max_length=250, null=True)),
                ('name', models.CharField(max_length=250)),
                ('full_name', models.TextField()),
                ('itinisere_id', models.IntegerField(unique=True)),
                ('metro_id', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='line',
            unique_together=set([('mode', 'name')]),
        ),
        migrations.AddField(
            model_name='direction',
            name='line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directions', to='transport.Line'),
        ),
        migrations.AlterUniqueTogether(
            name='direction',
            unique_together=set([('line', 'itinisere_id')]),
        ),
    ]
