# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 13:20
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_auto_20161026_0727'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insee_code', models.CharField(max_length=8, unique=True)),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='linestop',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(default=0, srid=4326),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='linestop',
            name='itinisere_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='stop',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='transport.City'),
        ),
    ]
