# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 15:11
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


def calc_points(apps, schema_editor):
    from transport.models import Stop # need logic
    for s in Stop.objects.all():
        if s.calc_point():
            s.save()


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0003_auto_20161028_1320'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ('name',)},
        ),

        # Add nullable stop.point
        migrations.AddField(
            model_name='stop',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(null=True, blank=True, srid=4326),
        ),

        # Build all initial values
        migrations.RunPython(calc_points),
    ]
