# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 14:06
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0004_auto_20161031_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='position',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
