# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-06 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0005_city_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='color_back',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='line',
            name='color_front',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
