# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-31 08:28
from __future__ import unicode_literals

import django.contrib.postgres.fields.hstore
from django.db import migrations


def update_providers(apps, schema_editor):
    """
    Update providers id from old keys
    to new Hstore
    """
    models = (
        'Direction',
        'Line',
        'LineStop',
        'Stop'
    )
    keys = {
        'itinisere_id': 'itinisere',
        'metro_id': 'metro',
        'metro_cluster': 'metro_cluster',
    }
    for m in models:
        model = apps.get_model('transport', m)
        print('Migrating {}'.format(m))
        for obj in model.objects.all():
            providers = {}
            for src, dest in keys.items():
                if not hasattr(obj, src):
                    continue
                providers[dest] = getattr(obj, src)
            if providers:
                obj.providers = providers
                obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0006_auto_20161206_1509'),
    ]

    operations = [
        # Add new providerd HStores
        migrations.AddField(
            model_name='direction',
            name='providers',
            field=django.contrib.postgres.fields.hstore.HStoreField(default=''),
        ),
        migrations.AddField(
            model_name='line',
            name='providers',
            field=django.contrib.postgres.fields.hstore.HStoreField(default=''),
        ),
        migrations.AddField(
            model_name='linestop',
            name='providers',
            field=django.contrib.postgres.fields.hstore.HStoreField(default=''),
        ),
        migrations.AddField(
            model_name='stop',
            name='providers',
            field=django.contrib.postgres.fields.hstore.HStoreField(default=''),
        ),

        # Migrate data from old providers to new ones
        migrations.RunPython(update_providers),
    ]
