# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-31 08:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0007_providers_part_1'),
    ]

    operations = [
        # Remove old providers id
        migrations.RemoveField(
            model_name='line',
            name='itinisere_id',
        ),
        migrations.RemoveField(
            model_name='line',
            name='metro_id',
        ),
        migrations.RemoveField(
            model_name='linestop',
            name='itinisere_id',
        ),
        migrations.RemoveField(
            model_name='stop',
            name='itinisere_id',
        ),
        migrations.RemoveField(
            model_name='stop',
            name='metro_cluster',
        ),
        migrations.RemoveField(
            model_name='stop',
            name='metro_id',
        ),
        #migrations.RemoveField(
        #    model_name='direction',
        #    name='itinisere_id',
        #),

        # Update constraint
        migrations.AlterUniqueTogether(
            name='direction',
            unique_together=set([('line', 'providers')]),
        ),
    ]
