# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-31 15:18
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0009_city_in_region'),
        ('region', '0001_initial'),
    ]

    state_operations = [
        migrations.AlterField(
            model_name='stop',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='region.City'),
        ),
    ]
