# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-31 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0010_auto_20170131_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='direction',
            name='region',
            field=models.CharField(choices=[('isere', 'Isere')], default='isere', max_length=50),
        ),
        migrations.AddField(
            model_name='line',
            name='region',
            field=models.CharField(choices=[('isere', 'Isere')], default='isere', max_length=50),
        ),
        migrations.AddField(
            model_name='linestop',
            name='region',
            field=models.CharField(choices=[('isere', 'Isere')], default='isere', max_length=50),
        ),
        migrations.AddField(
            model_name='stop',
            name='region',
            field=models.CharField(choices=[('isere', 'Isere')], default='isere', max_length=50),
        ),

        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='City',
                ),
            ]
        ),
    ]
