# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-01 17:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0011_auto_20170131_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='direction',
            name='itinisere_id',
        ),
        migrations.AlterField(
            model_name='stop',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='region.City'),
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='City',
                ),
            ]
        ),
    ]
