# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-07 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20170131_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='region',
            field=models.CharField(choices=[('isere', 'Isere')], default='isere', max_length=50),
        ),
    ]
