# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-17 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_location_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='twitter_secret',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='twitter_token',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
