# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20170519_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='region',
            field=models.CharField(choices=[('isere', 'Isere')], default='isere', max_length=50),
        ),
    ]
