# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-14 20:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_location_line_stops'),
        ('transport', '0004_auto_20161031_1511'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClockWidget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top', models.PositiveIntegerField()),
                ('left', models.PositiveIntegerField()),
                ('timezone', models.CharField(default='Europe/Paris', max_length=250)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LocationWidget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top', models.PositiveIntegerField()),
                ('left', models.PositiveIntegerField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='users.Location')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NoteWidget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top', models.PositiveIntegerField()),
                ('left', models.PositiveIntegerField()),
                ('text', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=100)),
                ('ratio', models.CharField(choices=[('16:9', 'Landscape 16x9'), ('9:16', 'Portrait 9x16')], default='16:9', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screens', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WeatherWidget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top', models.PositiveIntegerField()),
                ('left', models.PositiveIntegerField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_widgets', to='transport.City')),
                ('screen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weatherwidget', to='screen.Screen')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='notewidget',
            name='screen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notewidget', to='screen.Screen'),
        ),
        migrations.AddField(
            model_name='locationwidget',
            name='screen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locationwidget', to='screen.Screen'),
        ),
        migrations.AddField(
            model_name='clockwidget',
            name='screen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clockwidget', to='screen.Screen'),
        ),
        migrations.AlterUniqueTogether(
            name='screen',
            unique_together=set([('user', 'slug')]),
        ),
    ]
