# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 12:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

def remove_widgets(apps, schema_editor):
    """
    Remove all dummy widgets & screen
    """
    widgets = (
        apps.get_model('screen', 'ClockWidget'),
        apps.get_model('screen', 'NoteWidget'),
        apps.get_model('screen', 'LocationWidget'),
        apps.get_model('screen', 'WeatherWidget'),
        apps.get_model('screen', 'Screen'),
    )
    for w in widgets:
        w.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('screen', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(remove_widgets),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0)),
                ('vertical', models.BooleanField(default=False)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='screen.Group')),
                ('screen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='screen.Screen')),
            ],
        ),
        migrations.RemoveField(
            model_name='clockwidget',
            name='left',
        ),
        migrations.RemoveField(
            model_name='clockwidget',
            name='screen',
        ),
        migrations.RemoveField(
            model_name='clockwidget',
            name='top',
        ),
        migrations.RemoveField(
            model_name='locationwidget',
            name='left',
        ),
        migrations.RemoveField(
            model_name='locationwidget',
            name='screen',
        ),
        migrations.RemoveField(
            model_name='locationwidget',
            name='top',
        ),
        migrations.RemoveField(
            model_name='notewidget',
            name='left',
        ),
        migrations.RemoveField(
            model_name='notewidget',
            name='screen',
        ),
        migrations.RemoveField(
            model_name='notewidget',
            name='top',
        ),
        migrations.RemoveField(
            model_name='weatherwidget',
            name='left',
        ),
        migrations.RemoveField(
            model_name='weatherwidget',
            name='screen',
        ),
        migrations.RemoveField(
            model_name='weatherwidget',
            name='top',
        ),
        migrations.AddField(
            model_name='clockwidget',
            name='group',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='clockwidget', to='screen.Group'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='locationwidget',
            name='group',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='locationwidget', to='screen.Group'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notewidget',
            name='group',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='notewidget', to='screen.Group'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weatherwidget',
            name='group',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='weatherwidget', to='screen.Group'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='group',
            unique_together=set([('screen', 'parent', 'position')]),
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ('position',)},
        ),
    ]
