# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 16:48
from __future__ import unicode_literals

from django.db import migrations, models

import uuid

def remove_widgets(apps, schema_editor):
    """
    Remove all dummy widgets & screen
    """
    widgets = (
        apps.get_model('screen', 'ClockWidget'),
        apps.get_model('screen', 'NoteWidget'),
        apps.get_model('screen', 'LocationWidget'),
        apps.get_model('screen', 'WeatherWidget'),
        apps.get_model('screen', 'Screen'),
    )
    for w in widgets:
        w.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('screen', '0002_auto_20161118_1250'),
    ]

    operations = [
        migrations.RunPython(remove_widgets),
        migrations.AlterField(
            model_name='clockwidget',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='locationwidget',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='notewidget',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='weatherwidget',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
