# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-20 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screen', '0003_auto_20161118_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='screen',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
