# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 10:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('screen', '0005_screen_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screen',
            name='token',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterUniqueTogether(
            name='screen',
            unique_together=set([('user', 'slug'), ('slug', 'token')]),
        ),
    ]
