# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-13 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screen', '0008_screen_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='screen',
            name='is_template',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='screen',
            name='ratio',
        ),
    ]
