# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-16 10:29
from __future__ import unicode_literals

from django.db import migrations, models

def calc_positions(apps, schema_editor):
    from screen.models import Group
    for g in Group.objects.all():
        for i, w in enumerate(g.list_widgets()):
            w.position = i
            w.save()


class Migration(migrations.Migration):

    dependencies = [
        ('screen', '0009_screen_is_template'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clockwidget',
            options={'ordering': ('group', 'position')},
        ),
        migrations.AlterModelOptions(
            name='disruptionwidget',
            options={'ordering': ('group', 'position')},
        ),
        migrations.AlterModelOptions(
            name='locationwidget',
            options={'ordering': ('group', 'position')},
        ),
        migrations.AlterModelOptions(
            name='notewidget',
            options={'ordering': ('group', 'position')},
        ),
        migrations.AlterModelOptions(
            name='weatherwidget',
            options={'ordering': ('group', 'position')},
        ),
        migrations.AddField(
            model_name='clockwidget',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='disruptionwidget',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='locationwidget',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='notewidget',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='weatherwidget',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(calc_positions),
        migrations.AlterUniqueTogether(
            name='clockwidget',
            unique_together=set([('group', 'position')]),
        ),
        migrations.AlterUniqueTogether(
            name='disruptionwidget',
            unique_together=set([('group', 'position')]),
        ),
        migrations.AlterUniqueTogether(
            name='locationwidget',
            unique_together=set([('group', 'position')]),
        ),
        migrations.AlterUniqueTogether(
            name='notewidget',
            unique_together=set([('group', 'position')]),
        ),
        migrations.AlterUniqueTogether(
            name='weatherwidget',
            unique_together=set([('group', 'position')]),
        ),
    ]
