# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-16 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screen', '0010_auto_20161216_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationwidget',
            name='auto_pagination',
            field=models.BooleanField(default=False),
        ),
    ]
