# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-13 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screen', '0013_auto_20170222_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitterwidget',
            name='nb_tweets',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
